services:
  mysql:
    image: mysql:8.0
    container_name: piece
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      MYSQL_DATABASE: piece_db
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PW}
    volumes:
      - ./mysql_data:/var/lib/mysql