spring:
  application:
    name: java
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}
  security:
    oauth2:
      client:
        registration:
          google: # 구글이 아니더라도 아무 이름이나 상관없습니다.
            client-id: dummy-id
            client-secret: dummy-secret
            scope: profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub